In [ ]:
climate_data = [
    {"city": "City A", "temperature": 25, "carbon_footprint": 500},
    {"city": "City B", "temperature": 30, "carbon_footprint": 350},
    {"city": "City C", "temperature": 22, "carbon_footprint": 600},
    {"city": "City D", "temperature": 15, "carbon_footprint": 200},
    {"city": "City E", "temperature": 28, "carbon_footprint": 450},
]


In [ ]:
high_temp_threshold=25

high_temp_cities = [city["city"] for city in climate_data if city["temperature"] > high_temp_threshold]

print(high_temp_cities)
for city in climate_data:
    if city["temperature"] > high_temp_threshold:
        print(city["city"])

['City B', 'City E']
City B
City E


In [ ]:
total_carbon_footprint = 0
for city in climate_data:
    total_carbon_footprint += city["carbon_footprint"]

average_carbon_footprint = total_carbon_footprint / len(climate_data)

print(f"The average carbon footprint across all cities is: {average_carbon_footprint}")

The average carbon footprint across all cities is: 420.0


In [ ]:
highest_footprint_city = max(climate_data, key=lambda x: x["carbon_footprint"])
print("Highest carbon footprint city:", highest_footprint_city['city'])


Highest carbon footprint city: City C


In [ ]:
def calculate_carbon_footprint(energy_consumption, emission_factor):
    return energy_consumption * emission_factor
energy_consumption = 1000
emission_factor= 0.457
carbon_footprint = calculate_carbon_footprint(energy_consumption, emission_factor)
print(f"The carbon footprint: {carbon_footprint}kg CO2")

The carbon footprint: 457.0kg CO2


In [ ]:
value = input("Enter a value: ")

if type(value) is int:
    print("The input is an integer.")
else:
    print("The input is not an integer.")


Enter a value: 5
The input is not an integer.


In [ ]:
value = input("Enter a value: ")

if value[0] in ('-', '+') and value[1:].isdigit() or value.isdigit():
    print("The input is an integer.")
else:
    print("The input is not an integer.")


Enter a value: 5
The input is an integer.


In [ ]:
print("Select operation:")
print("1. Addition (+)")
print("2. Subtraction (-)")
print("3. Multiplication (*)")
print("4. Division (/)")

choice = input("Enter choice (1/2/3/4): ")
num1 = float(input("Enter the first number: "))
num2 = float(input("Enter the second number: "))

if choice == '1':
    print(f"addition is: {num1 + num2}")
elif choice == '2':
    print(f"subtraction is: {num1 - num2}")
elif choice == '3':
    print(f"multiplication is: {num1 * num2}")
elif choice == '4':
    if num2 != 0:
        print(f"division is: {num1 / num2}")
    else:
        print("Error.")



Select operation:
1. Addition (+)
2. Subtraction (-)
3. Multiplication (*)
4. Division (/)
Enter choice (1/2/3/4): 1
Enter the first number: 5
Enter the second number: 6
addition is: 11.0


In [ ]:
year = int(input("Enter a year: "))
def leap(year):
    return (lambda y: y % 4 == 0 and (y % 100 != 0 or y % 400 == 0))(year)
if leap(year):
    print(f"{year} is a leap year.")
else:
    print(f"{year} is not a leap year.")

Enter a year: 2004
2004 is a leap year.


In [ ]:
import pandas as pd



data = {
    "Project": ["Solar Farm A", "Wind Turbine X", "Hydropower Y", "Solar Roof Z", "Geothermal Plant P"],
    "Technology": ["Solar", "Wind", "Hydropower", "Solar", "Geothermal"],
    "Capacity (MW)": [150, 300, 200, 50, 100],  # Megawatts
    "Cost (Million $)": [200, 400, 350, 100, 250],  # Project cost
    "Location": ["California", "Texas", "Washington", "Nevada", "Idaho"],
    "Completion Year": [2023, 2024, 2022,2025,2023]
}

project_df = pd.DataFrame(data)
project_df.head()

Project  Technology  Capacity (MW)  Cost (Million $)  \
0        Solar Farm A       Solar            150               200   
1      Wind Turbine X        Wind            300               400   
2        Hydropower Y  Hydropower            200               350   
3        Solar Roof Z       Solar             50               100   
4  Geothermal Plant P  Geothermal            100               250   

     Location  Completion Year  
0  California             2023  
1       Texas             2024  
2  Washington             2022  
3      Nevada             2025  
4       Idaho             2023

In [ ]:
project_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   Project           5 non-null      object
 1   Technology        5 non-null      object
 2   Capacity (MW)     5 non-null      int64 
 3   Cost (Million $)  5 non-null      int64 
 4   Location          5 non-null      object
 5   Completion Year   5 non-null      int64 
dtypes: int64(3), object(3)
memory usage: 368.0+ bytes


In [ ]:
project_df.describe()

Capacity (MW)  Cost (Million $)  Completion Year
count        5.00000          5.000000         5.000000
mean       160.00000        260.000000      2023.400000
std         96.17692        119.373364         1.140175
min         50.00000        100.000000      2022.000000
25%        100.00000        200.000000      2023.000000
50%        150.00000        250.000000      2023.000000
75%        200.00000        350.000000      2024.000000
max        300.00000        400.000000      2025.000000

In [ ]:
import pandas as pd
project_df = pd.DataFrame(data)
high_Capacity_project = project_df[project_df['Capacity (MW)'] > 100]

In [ ]:
high_Capacity_project


Project  Technology  Capacity (MW)  Cost (Million $)    Location  \
0    Solar Farm A       Solar            150               200  California   
1  Wind Turbine X        Wind            300               400       Texas   
2    Hydropower Y  Hydropower            200               350  Washington   

   Completion Year  
0             2023  
1             2024  
2             2022

In [ ]:
pip install numpy

In [ ]:
!pip install numpy
import numpy as np

one_d_array = np.array([1,2,3,])
print(one_d_array)

[1 2 3]


In [ ]:
two_d_array = np.array([[1,2,3],[4,5,6]])
print(two_d_array)

[[1 2 3]
 [4 5 6]]


In [ ]:

print(one_d_array.shape)
one_d_array.shape

(3,)


(3,)

In [ ]:
print(two_d_array.shape)
two_d_array.shape

(2, 3)


(2, 3)

In [ ]:
import numpy as np

# Use np.full instead of npfull
array = np.full(5, 2.5)
print(array)

[2.5 2.5 2.5 2.5 2.5]


In [ ]:
identity_array = np.identity(4)
print(identity_array)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
array1 = np.arange(0,10,2)
print(array1)

[0 2 4 6 8]


In [ ]:
array2 = np.arange(5,15,2)
print(array2)

[ 5  7  9 11 13]


In [ ]:
linspace_array3 = np.linspace(2.0,3.0)
print(linspace_array3)

[2.         2.02040816 2.04081633 2.06122449 2.08163265 2.10204082
 2.12244898 2.14285714 2.16326531 2.18367347 2.20408163 2.2244898
 2.24489796 2.26530612 2.28571429 2.30612245 2.32653061 2.34693878
 2.36734694 2.3877551  2.40816327 2.42857143 2.44897959 2.46938776
 2.48979592 2.51020408 2.53061224 2.55102041 2.57142857 2.59183673
 2.6122449  2.63265306 2.65306122 2.67346939 2.69387755 2.71428571
 2.73469388 2.75510204 2.7755102  2.79591837 2.81632653 2.83673469
 2.85714286 2.87755102 2.89795918 2.91836735 2.93877551 2.95918367
 2.97959184 3.        ]


In [ ]:
text=input("enter a text:")
def is_palindrome(text):
    processed_text = ''.join(filter(str.isalnum, text)).lower()
    return processed_text == processed_text[::-1]

if is_palindrome(text):
        print("The text is a palindrome.")
else:
        print("The text is not a palindrome.")

enter a text:sos
The text is a palindrome.


In [ ]:
original_array = np.array([[1, 2, 3, 4, 5, 6]])
reshaped_2x3 = original_array.reshape(2, 3)
print("2x3:")
print(reshaped_2x3)
reshaped_3x2 = original_array.reshape(3, 2)
print("\n3x2:")
reshaped_3x2

2x3:
[[1 2 3]
 [4 5 6]]

3x2:


array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
flattened_array = original_array.flatten()
print("\nFlattened:")
flattened_array


Flattened:


array([1, 2, 3, 4, 5, 6])

In [ ]:
data = [10, 15, 12, 18, 20, 15, 22]
mean = np.mean(data)
print("Mean:", mean)



Mean: 16.0


In [ ]:
median = np.median(data)
print("Median:", median)


Median: 15.0


In [ ]:
# Calculate standard deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

Standard Deviation: 3.9641248358604595


In [ ]:
# Calculate variance
variance = np.var(data)
print("Variance:", variance)

Variance: 15.714285714285714


In [ ]:
import numpy as np
energy_consumption = np.array([1000, 1200, 900, 1500, 1100])
print(energy_consumption)

[1000 1200  900 1500 1100]


In [ ]:
median = np.median(energy_consumption)
print("Median:", median)

median = np.median(energy_consumption)
print("Median:", median)

# Calculate variance
variance = np.var(energy_consumption)
print("Variance:", variance)

Median: 1100.0
Median: 1100.0
Variance: 42400.0


In [ ]:
data = {
    "Energy Source": ["Solar", "Wind", "Hydropower", "Geothermal", "Biomass", "Nuclear"],
    "Energy Consumption (MWh)": [1200, np.nan, 2900, np.nan, 2500, 3200],
    "Cost (Million $)": [200, 400, np.nan, 150,250,np.nan]
}
cleaned_df = pd.DataFrame(data)
cleaned_df.head()

Energy Source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                    1200.0             200.0
1          Wind                       NaN             400.0
2    Hydropower                    2900.0               NaN
3    Geothermal                       NaN             150.0
4       Biomass                    2500.0             250.0

In [ ]:
cleaned_df['Energy Consumption (MWh)'] = cleaned_df['Energy Consumption (MWh)'].fillna(cleaned_df['Energy Consumption (MWh)'].mean())
cleaned_df['Cost (Million $)'] = cleaned_df['Cost (Million $)'].fillna(cleaned_df['Cost (Million $)'].mean())
cleaned_df

Energy Source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                    1200.0             200.0
1          Wind                    2450.0             400.0
2    Hydropower                    2900.0             250.0
3    Geothermal                    2450.0             150.0
4       Biomass                    2500.0             250.0
5       Nuclear                    3200.0             250.0

In [ ]:
cleaned_df = cleaned_df.fillna(method='ffill')
cleaned_df

<ipython-input-49-47a1bfc50588>:3: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  cleaned_df = cleaned_df.fillna(method='ffill')


Energy Source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                    1200.0             200.0
1          Wind                    2450.0             400.0
2    Hydropower                    2900.0             250.0
3    Geothermal                    2450.0             150.0
4       Biomass                    2500.0             250.0
5       Nuclear                    3200.0             250.0

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
energy_df = pd.DataFrame(data)
energy_df['Energy Consumption (MWh)'] = scaler.fit_transform(energy_df[['Energy Consumption (MWh)']])
energy_df

Energy Source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                      0.00             200.0
1          Wind                       NaN             400.0
2    Hydropower                      0.85               NaN
3    Geothermal                       NaN             150.0
4       Biomass                      0.65             250.0
5       Nuclear                      1.00               NaN

In [ ]:
import pandas as pd
import numpy as np
data = {
    "Energy Source": ["Solar", "Wind", "Hydropower", "Geothermal", "Biomass", "Nuclear"],
    "Energy Consumption (MWh)": [1200, np.nan, 2900, np.nan, 2500, 3200],
    "Cost (Million $)": [200, 400, np.nan, 150,250,np.nan]
}
energy_df = pd.DataFrame(data)
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
energy_df[["Energy Consumption (MWh)","Cost (Million $)"]] = scaler.fit_transform(
    energy_df[["Energy Consumption (MWh)","Cost (Million $)"]]
)
print("\nData After Normalization (XZ- score Scaling): ")
print(energy_df)


Data After Normalization (XZ- score Scaling): 
  Energy Source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                 -1.637804         -0.534522
1          Wind                       NaN          1.603567
2    Hydropower                  0.589610               NaN
3    Geothermal                       NaN         -1.069045
4       Biomass                  0.065512          0.000000
5       Nuclear                  0.982683               NaN


In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder

data = {
    "Energy Source": ["Solar", "Wind", "Hydropower", "Geothermal", "Biomass", "Nuclear"],
    "Energy Consumption (MWh)": [1200, np.nan, 2900, np.nan, 2500, 3200],
    "Cost (Million $)": [200, 400, np.nan, 150,250,np.nan]
}
energy_df = pd.DataFrame(data)

# Create a OneHotEncoder object
encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')

# Fit and transform the 'Energy Source' column
encoded_data = encoder.fit_transform(energy_df[['Energy Source']])

# Create a new DataFrame with the one-hot encoded features
encoded_df = pd.DataFrame(encoded_data, columns=encoder.get_feature_names_out(['Energy Source']))

# Concatenate the one-hot encoded features with the original DataFrame
energy_df = pd.concat([energy_df, encoded_df], axis=1)

# Display the updated DataFrame
energy_df

Energy Source  Energy Consumption (MWh)  Cost (Million $)  \
0         Solar                    1200.0             200.0   
1          Wind                       NaN             400.0   
2    Hydropower                    2900.0               NaN   
3    Geothermal                       NaN             150.0   
4       Biomass                    2500.0             250.0   
5       Nuclear                    3200.0               NaN   

   Energy Source_Biomass  Energy Source_Geothermal  Energy Source_Hydropower  \
0                    0.0                       0.0                       0.0   
1                    0.0                       0.0                       0.0   
2                    0.0                       0.0                       1.0   
3                    0.0                       1.0                       0.0   
4                    1.0                       0.0                       0.0   
5                    0.0                       0.0                       0.0   

   Energy Source_Nuclear  Energy Source_Solar  Energy Source_Wind  
0                    0.0                  1.0                 0.0  
1                    0.0                  0.0                 1.0  
2                    0.0                  0.0                 0.0  
3                    0.0                  0.0                 0.0  
4                    0.0                  0.0                 0.0  
5                    1.0                  0.0                 0.0